# Generated by Django 3.2.5 on 2021-08-17 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name_plural': 'Books'},
        ),
        migrations.RemoveField(
            model_name='books',
            name='related_tags',
        ),
        migrations.AddField(
            model_name='books',
            name='related_tags',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Books.categories'),
            preserve_default=False,
        ),
    ]
