# Generated by Django 3.2.5 on 2021-08-17 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_auto_20210817_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='athour',
            new_name='author',
        ),
    ]
