# Generated by Django 3.2.5 on 2021-08-17 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_rename_athour_books_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='related_tags',
            new_name='related_tag',
        ),
    ]
