# Generated by Django 3.2.5 on 2021-08-17 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0004_rename_related_tags_books_related_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='related_tag',
            new_name='related_category',
        ),
    ]
