# Generated by Django 3.2.5 on 2021-08-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0005_rename_related_tag_books_related_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='ISBN',
            field=models.CharField(default=123456509032456, max_length=255),
            preserve_default=False,
        ),
    ]
