# Generated by Django 3.2.5 on 2021-10-09 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0006_books_isbn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='long_summary',
            new_name='summary',
        ),
        migrations.RemoveField(
            model_name='books',
            name='short_summary',
        ),
    ]
