# Generated by Django 3.2.5 on 2021-10-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0007_auto_20211010_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
