# Generated by Django 3.2.5 on 2021-10-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0008_books_book_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='books/images'),
        ),
    ]
