# Generated by Django 3.2.5 on 2021-10-25 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0009_alter_books_thumbnail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Books',
        ),
    ]
