# Generated by Django 3.2.5 on 2021-10-25 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Books', '0010_delete_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('edition', models.CharField(max_length=255)),
                ('ISBN', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='books/images')),
                ('summary', models.TextField()),
                ('views', models.IntegerField(default=0)),
                ('book_link', models.CharField(blank=True, max_length=500, null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('related_category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Books.categories')),
            ],
            options={
                'verbose_name_plural': 'Books',
            },
        ),
    ]
