# Generated by Django 3.2.5 on 2021-12-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0011_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='link',
            field=models.CharField(default='N/A', max_length=1024),
        ),
        migrations.AlterField(
            model_name='books',
            name='ISBN',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='books',
            name='edition',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='books',
            name='publisher',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
