# Generated by Django 3.2.5 on 2021-08-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0002_alter_blogs_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.RenameField(
            model_name='blogs',
            old_name='related_tag',
            new_name='related_tags',
        ),
        migrations.AddField(
            model_name='blogs',
            name='related_categories',
            field=models.ManyToManyField(to='Blogs.Categories'),
        ),
    ]
