# Generated by Django 3.2.5 on 2021-08-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0003_auto_20210802_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
