# Generated by Django 3.2.5 on 2021-10-05 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0006_auto_20210815_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='RootComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentor', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blogs.blogs')),
            ],
            options={
                'verbose_name_plural': 'Root Comments',
            },
        ),
    ]
