# Generated by Django 3.2.5 on 2021-10-05 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0007_rootcomments'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_commentor', models.CharField(max_length=255)),
                ('reply_comment', models.TextField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('root_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blogs.rootcomments')),
            ],
            options={
                'verbose_name_plural': 'Reply Comments',
            },
        ),
    ]
