# Generated by Django 3.2.5 on 2021-10-06 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0008_replycomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='replycomments',
            name='blog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Blogs.blogs'),
            preserve_default=False,
        ),
    ]
