# Generated by Django 3.2.5 on 2021-10-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0009_replycomments_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='fifth_image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/images'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='first_image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/images'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='fourth_image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/images'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='second_image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/images'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='third_image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/images'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='thumbnail',
            field=models.ImageField(upload_to='blogs/images'),
        ),
    ]
