# Generated by Django 3.2.5 on 2021-08-13 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AboutUs', '0002_socialmedia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialMedia',
        ),
    ]
