# Generated by Django 3.2.5 on 2021-10-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutUs', '0003_delete_socialmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(upload_to='home/images'),
        ),
    ]
