# Generated by Django 3.2.5 on 2021-07-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonyAdding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=255)),
                ('author_email', models.CharField(max_length=255)),
                ('author_image', models.ImageField(upload_to='media/home/images')),
                ('testimony', models.TextField()),
                ('linkedin_profile', models.CharField(max_length=255)),
                ('facebook_profile', models.CharField(max_length=255)),
                ('twitter_profile', models.CharField(max_length=255)),
                ('instagram_profile', models.CharField(max_length=255)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Testimony Adding Section',
            },
        ),
    ]
