# Generated by Django 3.2.5 on 2021-07-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_testimonyadding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonyadding',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/home/images'),
        ),
        migrations.AlterField(
            model_name='testimonyadding',
            name='facebook_profile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testimonyadding',
            name='instagram_profile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testimonyadding',
            name='linkedin_profile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testimonyadding',
            name='twitter_profile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
