# Generated by Django 3.2.5 on 2021-10-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20210729_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebackground',
            name='image',
            field=models.ImageField(upload_to='home/images'),
        ),
        migrations.AlterField(
            model_name='homewelcoming',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='home/images'),
        ),
        migrations.AlterField(
            model_name='testimonyadding',
            name='author_image',
            field=models.ImageField(blank=True, default='/static/images/default.png', null=True, upload_to='home/images'),
        ),
    ]
