# Generated by Django 3.2.5 on 2021-10-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20211014_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonyadding',
            name='author_image',
            field=models.ImageField(blank=True, default='home/images/default.png', null=True, upload_to='home/images'),
        ),
    ]
