# Generated by Django 3.2.5 on 2021-12-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_testimonyadding_author_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonyadding',
            name='author_image',
            field=models.ImageField(blank=True, default='media/home/images/default.png', null=True, upload_to='home/images'),
        ),
    ]
